language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- nightly
install:
- pip install -r requirements.txt
script: python -m unittest discover -s tests
jobs:
  include:
    - stage: test
      script: python -m unittest discover -s tests
    - stage: publish
      script: python setup.py upload
deploy:
  provider: pypi
  user: paambaati
  password:
    secure: SPYEnIGqXmNOYsRz5lPktEdahWVShMV7akuMYz5UO7CnqpdmRVWHIynJ+Pl4iasMw862NM00beBeSv5aR06TgfDKHZ7FBTOZqVwCLQ3/U1hw5ycpGzSr5nZD+74BRS61oKuMv6r/ytk6zZZQpSeOg7AY8NHUiPfojlR3FyoPkeK5Tp+HA4dOku/wnqxLjCMlo/OBcIq78wN1mM5w/sAdrnucVPIl4ZjBSQ9W30HhEllQ7lTYAhijG5cjQQqeFu9PLB68/89LmfER6EpDfAysvC0Yqfb47cz33kCv1u3fSAHwCh7XnGynUD9woEgwMLbwaHKgircEBmaFgSEqTuZybn4hKDOpjSH86ub6BpfvcdjLVyspzkXKJj02kAaDjDuDZDuZorj8W/14Xu0W4pMUp3pMJFttvLiQG1Ee+DQaMG9DALzQuPMZbv3Y0zTHbCe7ywS13hZL46kwR4nBGXwsoz4g0vK+GKLEE3MYW2rAud7uevo20WFmp+F41qPBTlXfDM362Gi7y0GcYLjYTX5k/kYgOVqWP19KoRxskayCaRijtUha4p+GkILq9Fx1puAVLdiewVkdmPfWN2oIsqr/SmKX5F1zVYk74FST1VJR1coDP9bkruEsWFfuJa3Mh3Mz4jvd/urhXxJDSh61Ejvh0EPfiGtmKsVtlSPOVN13XV0=
  on:
    tags: true
    branch: master
