dist: xenial
language: python
python:
- nightly
- '3.7'
- '3.6'
- '3.5'
- '3.4'
- '2.7'
cache: pip
install:
- pip install -r requirements.txt
script: python -m unittest discover -s tests
stages:
  - test
  - publish
jobs:
  include:
    - stage: publish
      python: 2.7
      install: skip
      script: skip
      deploy:
        provider: pypi
        distributions: "sdist bdist_egg bdist_wheel"
        skip_cleanup: true
        user: paambaati
        password:
          secure: iAz5Xru6zhcRRVpDcw/TUFfUkSj7bfTIYDfpwAs4zZidlSHf8NnJQo+VXIJk5Jx6xZMv8e99QHQ+GeXcxd3R3n1/5w/ZckVl8/KCrj4lr3l1eBO1nK86TNFrXa6BdZLKRoK3I5JgBijivhmNC6dP3hdtzVke5DkAh2//Jhiht6bIZDiMHEK4wBo3K8M/PE0lx1/3ttyq+EVv0DotAZhHQCrFXJtlHStKxbyfJ1Mm7tFJXdp0+cItTGWy3Pd+p4qDW10OhPWr+0YG4SievPLVTVExQJWrG25SOJQMrnCICGrPs9pjkHhqDvnt1Fc2Xo2neqzA2IG2GOrdN1mfi1thgQli76tuOeIRJr8ue9MaVxMBhwzrXm/w6rL/vfGclFqNlj/2uMgjeUurBcOACpDufjv6CJVxdJm8RYoTlrOo3FnpuJUy8llCC62JuqvMrgxPKiwU7kYgcJAYYBonNgaxIfiPqax7KOs2hojXUyHJYXvLnqiE1JLZoETLlekixOf+DcDoXUggTAStrkEuvQaQ7NiE/gD8Hzlg3n4CZUl0cW/sK2jT2OrKgqGIB05pg07u3t0gSTjmSd9JZtDPuMv0v1QZ+bNwTh8ifdaKsrzIS1bWdrGnJvykEST1UtE+p/AIAifZ8A+z8ov8A35iQE06n2vgO4vxLXRcyOe5+mOKuGA=
        on:
          branch: master
