dist: xenial
language: python
python:
- nightly
- '3.7'
- '3.6'
- '3.5'
- '2.7'
cache: pip
env:
  global:
    - CC_TEST_REPORTER_ID=fd2fa0062111734e11f6e162e976868bf5a702dac56be26da67d8929b5c9c2e0
before_install:
  - sudo apt-get install -y python-dev gcc
  - sudo apt-get install -y python3-dev gcc
install:
  - pip install coverage
  - pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: coverage run -m unittest discover -s tests
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
stages:
  - test
  - publish
jobs:
  include:
    - stage: publish
      python: 2.7
      install: skip
      script: skip
      deploy:
        provider: pypi
        distributions: "sdist bdist_egg bdist_wheel"
        skip_cleanup: true
        skip_existing: true
        user: paambaati
        password:
          secure: "vcErzsQgMO462Uhdiv6Sl3vMUgItPNFgZo4pH4jg4UNDzqGfct2co63jeZOMs5qjxhdhGV45AcK+vWbsqynjOqxQijEf5ej6+QIICc/Y+q8zH18ladXgnb89mIPzaXk6qRgXQb3rHmsqopQirWZqXUPHQMsltAQUlEYQUrlYvuzhUVrJ444LMvCylJOgeGLMmsZF7Whq7yQE1Kr0mNBCSczijeGBuOYtkukMFe9Cd2T0EiM/wTRv5WK0gvcngP1yBfwVWQGZiLZGYfSbW3TctjQZmzD2NJckFnc18QIoZKmm1F1PAhbhA14u6bfSbyJmVUuyaLMuPl8iO0UUoz1QOT4DcK6ea/5BdMM8h++OXdqJMK1ZaI9tAit5Pms9IP1pxxtyvGlE0JeRM+UgnaNdLTTEpY6fIxFuR5sGMj+d720yWIED3EuStLJHLow0DpYKRFM0h9lbT3cmEYg/wzEOs2eZuURCtPM+bLQbbWE80VkddqGExAxMAq6Cm2ezG4ln1KaWPcyQbLiqX489G51I1RHVw7BZENDNhNdFI6xuOhVX47ms3buWK9MCfCUbcCMmNYZUAyKAEWKPOZ3TTN5l/OTU4+Gr5Nnz/GMHtEKVmcxfsTrnyKqQRym0+pC4JEui9xX/uKwkjwkH/QwXPQDDgoHc0arBqSLtsd8EtEajR14="
        on:
          branch: master
